Update unit test for new pygithub API
A change to the API caused the test to fail:

```
>       mocker.patch.object(Github, "get_repo", side_effect=github.UnknownObjectException(status=42, data="foo"))
E       TypeError: __init__() missing 1 required positional argument: 'headers'
```